### ISSUE TITLE
make test-release error TEETxEngine: Failed to init quote.

### ISSUE THREAD

**Issue by xiaolese1** [hkbudb/slimchain#3]
Hello, very exciting job. When I run make test-release, I always get this error

`     Running unittests src/lib.rs (target/release/deps/slimchain_tx_engine_tee-afc2343156d20546)

running 1 test
2023-05-16T13:19:17.645484Z  INFO slimchain_tx_engine_tee::engine: Init SGX enclave from /home/h3c/slimchain/target/release/libslimchain_tx_engine_tee_enclave.signed.so.
thread 'tests::test' panicked at 'called `Result::unwrap()` on an `Err` value: TEETxEngine: Failed to init quote. SGX error SGX_ERROR_UNRECOGNIZED_PLATFORM.', slimchain-tx-engine-tee/src/tests.rs:36:79
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
test tests::test ... FAILED

failures:

failures:
    tests::test

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1.79s`

I already create a comfig.toml in root directory, and get the Product DEV Intel® Software Guard Extensions Attestation Service (Linkable) subscription SPID and Primary key filled in. what did I miss? 
Sincerely

**Comment by xiaolese1** [comment]
I am working on ubuntu 20.04 and cpu: Intel(R) Xeon(R) Gold 6330 CPU @ 2.00GHz 
and I tried sudo ./scripts/install_sgx_driver.sh this scripts but when install SGX deiver, this error happend 

Building module:
cleaning build area...
'make' KDIR=/lib/modules/5.15.0-58-generic/build...(bad exit status: 2)

Failed to build driver.
DKMS make.log for sgx-1.41 for kernel 5.15.0-58-generic (x86_64)

**Comment by xiaolese1** [comment]
Oh I firgure it out, after kernel 5.11 linux has includes the SGX In-Kernel driver. So, may be the SGX_ERROR_UNRECOGNIZED_PLATFORM error is not because the sgx_driver. 
but still don't know why?

**Comment by xu-cheng** [comment]
I haven't maintained this project for a while. I guess your problem may be due to SGX SDK or Rust SGX SDK. Both of them are a bit unstable.  

May I suggest to run the hello-world example in Rust SGX SDK? It is a simpler program, which can help you to validate the SGX setup. You may also try to upgrade the Rust SGX SDK used by this project to the latest upstream git commit.

**Comment by xiaolese1** [comment]
> I haven't maintained this project for a while. I guess your problem may be due to SGX SDK or Rust SGX SDK. Both of them are a bit unstable.
> 
> May I suggest to run the hello-world example in Rust SGX SDK? It is a simpler program, which can help you to validate the SGX setup. You may also try to upgrade the Rust SGX SDK used by this project to the latest upstream git commit.

Thank you for your replay! I have some questions about Slimchain, and I would greatly appreciate it if you could answer them for me.

1. Slimchain obtains read-write sets by executing transactions in sgx. Is there any status information in enclave at this time? Assuming not, how can we solve certain situations that rely on judgment statements to determine the state of acquisition? If a>10 return a else return b. Is it time to read a or b?

2. I saw a transaction in the code about creating a contract, and I understand that the contract address can be directly calculated when there is no status information. However, how to generate a proof for the new contract address? Should there be no corresponding state for this new address in the state trie at this time?

3. Is it possible to complete the entire process of block creation in SGX? I want to rebuild a partial MPT in enclave with proof as the database for transaction execution, and then generate a new block

**Comment by xu-cheng** [comment]
>Slimchain obtains read-write sets by executing transactions in sgx. Is there any status information in enclave at this time? Assuming not, how can we solve certain situations that rely on judgment statements to determine the state of acquisition? If a>10 return a else return b. Is it time to read a or b?

Transactions are always executed against current world state. The enclave will invoke ocall to access the current state stored in the blockchain.

>I saw a transaction in the code about creating a contract, and I understand that the contract address can be directly calculated when there is no status information. However, how to generate a proof for the new contract address? Should there be no corresponding state for this new address in the state trie at this time?

Creating a contract is just a smart contract transaction. It is handled like normal transaction. Again, all transactions are executed against current world state.

>Is it possible to complete the entire process of block creation in SGX? I want to rebuild a partial MPT in enclave with proof as the database for transaction execution, and then generate a new block

Of course, it is possible. But it is outside the scope of this project.
